### ISSUE TITLE
2014-02-25 XrdSfs, XrsOfs ... XrdOss confusion

### ISSUE THREAD

**Issue by alja** [alja/xrootd#4]
Code observation:
- XrdSfs purely abstract (existis SfsNative ... ? is this native physical file system)
- XrdOfs inherited from XrdSfs, uses XrdOss
- XrdOss not related to Sfs, OS dependent

See http://xrootd.org/papers/Scalla-Intro.pdf

**Comment by alja** [comment]
#0  XrdFileCache::Cache::Attach (this=0x649e20, io=0x7fffe0003910, Options=0) at /home/alja/test-master/xrootd/src/XrdFileCache/XrdFileCache.cc:142
#1  0x00007ffff65c35a2 in XrdPosixFile::Finalize (this=0x7fffe00030f0, Status=0x0) at /home/alja/test-master/xrootd/src/XrdPosix/XrdPosixFile.cc:249
#2  0x00007ffff65c8b46 in (anonymous namespace)::OpenDefer (fp=0x7fffe00030f0, cbP=0x0, XOflags=XrdCl::OpenFlags::Read, XOmode=XrdCl::Access::None, isStream=false)
    at /home/alja/test-master/xrootd/src/XrdPosix/XrdPosixXrootd.cc:113
#3  0x00007ffff65c9d6b in XrdPosixXrootd::Open (path=0x7ffff720a9a0 "root://24@mongo.t2.ucsd.edu:1094//test/0001.root?oss.lcl=1", oflags=0, mode=384, cbP=0x0)
    at /home/alja/test-master/xrootd/src/XrdPosix/XrdPosixXrootd.cc:526
#4  0x00007ffff69fc295 in XrdPssFile::Open (this=0x7fffe00030c0, path=0x7fffe0002400 "/test/0001.root", Oflag=0, Mode=384, Env=...) at /home/alja/test-master/xrootd/src/XrdPss/XrdPss.cc:681
#5  0x00007ffff7d752c6 in XrdOfsFile::open (this=0x7fffe0002810, path=0x7fffe0002400 "/test/0001.root", open_mode=0, Mode=384, client=0x7fffe0002090, info=0x0)
    at /home/alja/test-master/xrootd/src/XrdOfs/XrdOfs.cc:611
#6  0x00007ffff7d68773 in XrdXrootdProtocol::do_Open (this=0x7fffe0001fd0) at /home/alja/test-master/xrootd/src/XrdXrootd/XrdXrootdXeq.cc:1279
#7  0x00007ffff7d5bd55 in XrdXrootdProtocol::Process2 (this=0x7fffe0001fd0) at /home/alja/test-master/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:509
#8  0x00007ffff7d5b6e5 in XrdXrootdProtocol::Process (this=0x7fffe0001fd0, lp=0x7fffe0000a08) at /home/alja/test-master/xrootd/src/XrdXrootd/XrdXrootdProtocol.cc:404
#9  0x00007ffff7ac45ba in XrdLink::DoIt (this=0x7fffe0000a08) at /home/alja/test-master/xrootd/src/Xrd/XrdLink.cc:397
#10 0x00000000004102e5 in XrdMain::DoIt (this=0x7fffffffde20) at /home/alja/test-master/xrootd/src/Xrd/XrdMain.cc:99
#11 0x00007ffff7aca74e in XrdScheduler::Run (this=0x614778) at /home/alja/test-master/xrootd/src/Xrd/XrdScheduler.cc:357
#12 0x00007ffff7ac994e in XrdStartWorking (carg=0x614778) at /home/alja/test-master/xrootd/src/Xrd/XrdScheduler.cc:87
#13 0x00007ffff7a78462 in XrdSysThread_Xeq (myargs=0x626680) at /home/alja/test-master/xrootd/src/XrdSys/XrdSysPthread.cc:86
#14 0x0000003b99807aa1 in start_thread () from /lib64/libpthread.so.0
#15 0x0000003b994e8aad in clone () from /lib64/libc.so.6
